export interface CatalogProduct {
  id: string;
  name: string;
  slug: string;
  price: number;
  originalPrice?: number;
  discount?: number;
  images: string[];
  category: string;
  subcategory?: string;
  brand: string;
  rating: number;
  reviewCount: number;
  description?: string;
  inStock: boolean;
  isNew?: boolean;
  isBestSeller?: boolean;
}

const baseProducts: CatalogProduct[] = [
  {
    id: 'p1',
    name: 'iPhone 15 Pro Max 256GB',
    slug: 'iphone-15-pro-max-256gb',
    price: 31990000,
    originalPrice: 34990000,
    discount: 9,
    images: ['/images/products/dien-thoai/iphone-15-pro-max-256gb.png'],
    category: 'dien-thoai',
    subcategory: 'iphone',
    brand: 'Apple',
    rating: 4.9,
    reviewCount: 428,
    inStock: true,
    isBestSeller: true,
  },
  {
    id: 'p2',
    name: 'Samsung Galaxy S24 Ultra',
    slug: 'samsung-galaxy-s24-ultra',
    price: 28990000,
    originalPrice: 31990000,
    discount: 9,
    images: ['/images/products/dien-thoai/samsung-galaxy-s24-ultra.png'],
    category: 'dien-thoai',
    subcategory: 'samsung',
    brand: 'Samsung',
    rating: 4.8,
    reviewCount: 397,
    inStock: true,
    isBestSeller: true,
  },
  {
    id: 'p3',
    name: 'MacBook Air 15 inch M2',
    slug: 'macbook-air-15-m2',
    price: 32990000,
    originalPrice: 35990000,
    discount: 8,
    images: ['/images/products/laptop/macbook-air-15-m2.png'],
    category: 'laptop',
    subcategory: 'macbook',
    brand: 'Apple',
    rating: 4.9,
    reviewCount: 311,
    inStock: true,
    isNew: true,
  },
  {
    id: 'p4',
    name: 'Tivi Samsung QLED 4K 65 inch QA65Q60C',
    slug: 'tivi-samsung-qled-4k-65-inch-qa65q60c',
    price: 17990000,
    originalPrice: 21990000,
    discount: 18,
    images: ['/images/products/tivi/tivi-samsung-qled-4k-65-inch-qa65q60c.png'],
    category: 'tivi',
    subcategory: 'qled-4k',
    brand: 'Samsung',
    rating: 4.7,
    reviewCount: 256,
    inStock: true,
    isBestSeller: true,
  },
  {
    id: 'p5',
    name: 'Tivi LG 4K 55 inch 55UR8050PSB',
    slug: 'tivi-lg-4k-55-inch-55ur8050psb',
    price: 11990000,
    originalPrice: 14990000,
    discount: 20,
    images: ['/images/products/tivi/tivi-lg-4k-55-inch-55ur8050psb.png'],
    category: 'tivi',
    subcategory: 'smart-tv',
    brand: 'LG',
    rating: 4.6,
    reviewCount: 218,
    inStock: true,
  },
  {
    id: 'p6',
    name: 'Tủ lạnh Samsung Inverter 382L RT38CG6584B1SV',
    slug: 'tu-lanh-samsung-inverter-382-lit-rt38cg6584b1sv',
    price: 11890000,
    originalPrice: 14590000,
    discount: 19,
    images: ['/images/products/tu-lanh/tu-lanh-samsung-inverter-382-lit-rt38cg6584b1sv.png'],
    category: 'tu-lanh',
    subcategory: 'inverter',
    brand: 'Samsung',
    rating: 4.7,
    reviewCount: 193,
    inStock: true,
  },
  {
    id: 'p7',
    name: 'Tủ lạnh Aqua Inverter 189L AQR-T219FA(PB)',
    slug: 'tu-lanh-aqua-inverter-189-lit-aqr-t219fa-pb',
    price: 6490000,
    originalPrice: 7790000,
    discount: 17,
    images: ['/images/products/tu-lanh/tu-lanh-aqua-inverter-189-lit-aqr-t219fa-pb.png'],
    category: 'tu-lanh',
    subcategory: 'top-freezer',
    brand: 'Aqua',
    rating: 4.5,
    reviewCount: 167,
    inStock: true,
  },
  {
    id: 'p8',
    name: 'Máy lạnh Daikin Inverter 1 HP ATKF25XVMV',
    slug: 'may-lanh-daikin-inverter-1-hp-atkf25xvmv',
    price: 9990000,
    originalPrice: 12490000,
    discount: 20,
    images: ['/images/products/dieu-hoa/may-lanh-daikin-inverter-1-hp-atkf25xvmv.png'],
    category: 'dieu-hoa',
    subcategory: '1-chieu',
    brand: 'Daikin',
    rating: 4.7,
    reviewCount: 212,
    inStock: true,
    isBestSeller: true,
  },
  {
    id: 'p9',
    name: 'Máy lạnh Panasonic Inverter 1 HP CU/CS-PU9XKH-8M',
    slug: 'may-lanh-panasonic-inverter-1-hp-cu-cs-pu9xkh-8m',
    price: 10990000,
    originalPrice: 13290000,
    discount: 17,
    images: ['/images/products/dieu-hoa/may-lanh-panasonic-inverter-1-hp-cu-cs-pu9xkh-8m.png'],
    category: 'dieu-hoa',
    subcategory: '1-chieu',
    brand: 'Panasonic',
    rating: 4.8,
    reviewCount: 176,
    inStock: true,
  },
  {
    id: 'p10',
    name: 'Máy giặt LG AI DD Inverter 10kg FV1410S4P',
    slug: 'may-giat-lg-ai-dd-inverter-10-kg-fv1410s4p',
    price: 11490000,
    originalPrice: 13990000,
    discount: 18,
    images: ['/images/products/may-giat/may-giat-lg-ai-dd-inverter-10-kg-fv1410s4p.png'],
    category: 'may-giat',
    subcategory: 'inverter-washer',
    brand: 'LG',
    rating: 4.8,
    reviewCount: 203,
    inStock: true,
    isBestSeller: true,
  },
  {
    id: 'p11',
    name: 'Máy giặt Electrolux Inverter 9kg EWF9024P5WB',
    slug: 'may-giat-electrolux-inverter-9-kg-ewf9024p5wb',
    price: 9490000,
    originalPrice: 11790000,
    discount: 20,
    images: ['/images/products/may-giat/may-giat-electrolux-inverter-9-kg-ewf9024p5wb.png'],
    category: 'may-giat',
    subcategory: 'inverter-washer',
    brand: 'Electrolux',
    rating: 4.6,
    reviewCount: 159,
    inStock: true,
  },
  {
    id: 'p12',
    name: 'Nồi cơm điện tử Sharp 1.8L KS-COM18V',
    slug: 'noi-com-dien-tu-sharp-18-lit-ks-com18v',
    price: 1790000,
    originalPrice: 2290000,
    discount: 22,
    images: ['/images/products/gia-dung/noi-com-dien-tu-sharp-18-lit-ks-com18v.png'],
    category: 'gia-dung',
    subcategory: 'noi-com',
    brand: 'Sharp',
    rating: 4.5,
    reviewCount: 244,
    inStock: true,
  },
  {
    id: 'p13',
    name: 'Lò vi sóng Sharp 20 lít',
    slug: 'lo-vi-song-sharp-20-lit',
    price: 1490000,
    originalPrice: 1890000,
    discount: 21,
    images: ['/images/products/gia-dung/lo-vi-song-sharp-20-lit.png'],
    category: 'gia-dung',
    subcategory: 'may-xay',
    brand: 'Sharp',
    rating: 4.4,
    reviewCount: 132,
    inStock: true,
  },
  {
    id: 'p14',
    name: 'OPPO Reno11 F 5G',
    slug: 'oppo-reno11-f-5g',
    price: 8990000,
    originalPrice: 10490000,
    discount: 14,
    images: ['/images/products/dien-thoai/oppo-reno11-f-5g.png'],
    category: 'dien-thoai',
    subcategory: 'oppo',
    brand: 'OPPO',
    rating: 4.5,
    reviewCount: 176,
    inStock: true,
    isNew: true,
  },
  {
    id: 'p15',
    name: 'Xiaomi 14 5G',
    slug: 'xiaomi-14-5g',
    price: 16990000,
    originalPrice: 18990000,
    discount: 11,
    images: ['/images/products/dien-thoai/xiaomi-14-5g.png'],
    category: 'dien-thoai',
    subcategory: 'xiaomi',
    brand: 'Xiaomi',
    rating: 4.7,
    reviewCount: 201,
    inStock: true,
  },
];

export const products: CatalogProduct[] = baseProducts;
